server:
  error:
    whitelabel:
      enabled: false
    path: /error
    include-message: always
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always
spring:
  data:
    mongodb:
      database: BBDD_AExVeS
      host: localhost
      password: ''
      port: 27017
      username: root
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
springdoc:
    swagger-ui:
      operationsSorter: method
      tagsSorter: alpha